version: '3'
services:

  mdb-client:
    image: landscapedatacommons/dima-export:1.0.0
    build:
      context: .
      dockerfile: ./client.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: client
    # ports:
    #  - 5432:5432
    volumes:
     - ./client-bind:/client-bind
    # networks:
    #   - pg-network

# networks:
#   pg-network:
#     external: true

# volumes:
#   mdb_test_pg_data:
#     external: true