version: '3'
services:

  mdb-db:
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
     - 5434:5432
    volumes:
     - ./db-bind:/db-bind
     - mdb_test_pg_data:/var/lib/postgresql/data
    # networks:
    #   - pg-network
  mdb-client:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_PASSWORD: client
    # ports:
    #  - 5432:5432
    volumes:
     - ./client-bind:/client-bind
    # networks:
    #   - pg-network

# networks:
#   pg-network:
#     external: true

volumes:
  mdb_test_pg_data:
    external: true